default: &default
  adapter: mysql
  host: <%= ENV["MYSQL_HOST"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <% ENV["MYSQL_USER"] %>
  password: <% ENV["MYSQL_PASSWORD"] %>
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  database: aw_devel

production:
  <<: *default